const mockTopics = [
  {
    id: 1,
    name: 'Climate Change',
    dateCreated: '2023-08-15',
    commentsCount: 25,
    category: 'Environment',
  },
  {
    id: 2,
    name: 'Artificial Intelligence Ethics',
    dateCreated: '2023-08-16',
    commentsCount: 42,
    category: 'Technology',
  },
  {
    id: 3,
    name: 'Global Economics',
    dateCreated: '2023-08-17',
    commentsCount: 18,
    category: 'Finance',
  },
  {
    id: 4,
    name: 'Renewable Energy Sources',
    dateCreated: '2023-08-18',
    commentsCount: 30,
    category: 'Environment',
  },
  {
    id: 5,
    name: 'Cybersecurity Challenges',
    dateCreated: '2023-08-19',
    commentsCount: 35,
    category: 'Technology',
  },
  {
    id: 6,
    name: 'Space Exploration',
    dateCreated: '2023-08-20',
    commentsCount: 28,
    category: 'Science',
  },
  {
    id: 7,
    name: 'Mental Health Awareness',
    dateCreated: '2023-08-21',
    commentsCount: 50,
    category: 'Health',
  },
  {
    id: 8,
    name: 'Sustainable Urban Planning',
    dateCreated: '2023-08-22',
    commentsCount: 22,
    category: 'Environment',
  },
  {
    id: 9,
    name: 'Cryptocurrency Regulations',
    dateCreated: '2023-08-23',
    commentsCount: 38,
    category: 'Finance',
  },
  {
    id: 10,
    name: 'Genetic Engineering',
    dateCreated: '2023-08-24',
    commentsCount: 45,
    category: 'Science',
  },
  {
    id: 11,
    name: 'Online Privacy',
    dateCreated: '2023-08-25',
    commentsCount: 33,
    category: 'Technology',
  },
  {
    id: 12,
    name: 'Global Education Inequality',
    dateCreated: '2023-08-26',
    commentsCount: 27,
    category: 'Education',
  },
  {
    id: 13,
    name: 'Sustainable Fashion',
    dateCreated: '2023-08-27',
    commentsCount: 20,
    category: 'Environment',
  },
  {
    id: 14,
    name: 'Future of Work',
    dateCreated: '2023-08-28',
    commentsCount: 40,
    category: 'Society',
  },
  {
    id: 15,
    name: 'Quantum Computing',
    dateCreated: '2023-08-29',
    commentsCount: 15,
    category: 'Technology',
  },
  {
    id: 16,
    name: 'Ocean Conservation',
    dateCreated: '2023-08-30',
    commentsCount: 32,
    category: 'Environment',
  },
  {
    id: 17,
    name: 'Autonomous Vehicles',
    dateCreated: '2023-08-31',
    commentsCount: 28,
    category: 'Technology',
  },
  {
    id: 18,
    name: 'Universal Basic Income',
    dateCreated: '2023-09-01',
    commentsCount: 55,
    category: 'Finance',
  },
  {
    id: 19,
    name: 'Renewable Energy Storage',
    dateCreated: '2023-09-02',
    commentsCount: 23,
    category: 'Technology',
  },
  {
    id: 20,
    name: 'Digital Art and NFTs',
    dateCreated: '2023-09-03',
    commentsCount: 37,
    category: 'Art',
  },
  {
    id: 21,
    name: 'Space Tourism',
    dateCreated: '2023-09-04',
    commentsCount: 30,
    category: 'Travel',
  },
  {
    id: 22,
    name: 'Sustainable Agriculture',
    dateCreated: '2023-09-05',
    commentsCount: 25,
    category: 'Environment',
  },
  {
    id: 23,
    name: 'Blockchain in Healthcare',
    dateCreated: '2023-09-06',
    commentsCount: 18,
    category: 'Health',
  },
  {
    id: 24,
    name: 'Remote Work Culture',
    dateCreated: '2023-09-07',
    commentsCount: 42,
    category: 'Business',
  },
  {
    id: 25,
    name: 'Circular Economy',
    dateCreated: '2023-09-08',
    commentsCount: 29,
    category: 'Environment',
  },
  {
    id: 26,
    name: 'Augmented Reality in Education',
    dateCreated: '2023-09-09',
    commentsCount: 31,
    category: 'Education',
  },
  {
    id: 27,
    name: 'Ethical Consumerism',
    dateCreated: '2023-09-10',
    commentsCount: 36,
    category: 'Society',
  },
  {
    id: 28,
    name: 'Telemedicine',
    dateCreated: '2023-09-11',
    commentsCount: 24,
    category: 'Health',
  },
  {
    id: 29,
    name: 'Dark Matter Research',
    dateCreated: '2023-09-12',
    commentsCount: 17,
    category: 'Science',
  },
  {
    id: 30,
    name: 'Social Media and Mental Health',
    dateCreated: '2023-09-13',
    commentsCount: 48,
    category: 'Health',
  },
];

export default mockTopics;
